"""
Generate synthetic financial datasets for portfolio demonstration.

This project does not contain or reproduce confidential source data.
All records generated by this script are artificial and are intended
only to demonstrate analytics engineering and BI techniques.
"""

from pathlib import Path

import numpy as np
import pandas as pd


SEED = 42

N_CUSTOMERS = 10_000
N_APPLICATIONS = 30_000
N_TRANSACTIONS = 233_000
N_DEVICES = 15_000

START_DATE = pd.Timestamp("2023-05-30")
END_DATE = pd.Timestamp("2025-05-29")

OUTPUT_DIR = Path(__file__).resolve().parents[1] / "data" / "generated"


rng = np.random.default_rng(SEED)


REGIONS = [
    "Vancouver",
    "Surrey",
    "Burnaby",
    "Richmond",
    "Victoria",
    "Kelowna",
    "Abbotsford",
    "Nanaimo",
    "Coquitlam",
    "Port Coquitlam",
    "White Rock",
    "Prince George",
    "Maple Ridge",
    "Chilliwack",
    "Kamloops",
]

CUSTOMER_TYPES = ["Basic", "Advance", "Premium"]

JOB_TYPES = [
    "Software Developer",
    "Engineer",
    "Manager",
    "Doctor",
    "Nurse",
    "Technician",
    "Veterinarian",
]

LOAN_PURPOSES = [
    "Debt Consolidation",
    "Car Loan",
    "Wedding",
    "Home Renovation",
    "Medical Expenses",
    "Travel",
    "Emergency",
]

MERCHANT_CATEGORIES = [
    "Transfer",
    "ATM",
    "Electronics",
    "Food",
    "Travel",
    "Retail",
    "Entertainment",
]

TRANSACTION_TYPES = [
    "Purchase",
    "Transfer",
    "Withdrawal",
    "Payment",
    "Return",
]

APPLICATION_FRAUD_REASONS = [
    "Document",
    "Identity",
    "Location",
]

TRANSACTION_FRAUD_REASONS = [
    "Amount Anomaly",
    "Velocity",
    "Location Mismatch",
    "Manual Review",
]


def random_dates(size: int) -> pd.Series:
    days = (END_DATE - START_DATE).days

    offsets = rng.integers(
        low=0,
        high=days + 1,
        size=size
    )

    return START_DATE + pd.to_timedelta(offsets, unit="D")


def generate_devices() -> pd.DataFrame:
    device_ids = np.arange(1, N_DEVICES + 1)

    prior_fraud = rng.choice(
        [0, 1],
        size=N_DEVICES,
        p=[0.94, 0.06]
    )

    return pd.DataFrame(
        {
            "device_id": device_ids,
            "device_type": rng.choice(
                ["Mobile", "Desktop", "Tablet"],
                size=N_DEVICES,
                p=[0.65, 0.28, 0.07],
            ),
            "has_prior_fraud_flag": prior_fraud,
        }
    )


def generate_customers() -> pd.DataFrame:
    customer_ids = np.arange(1, N_CUSTOMERS + 1)

    age = rng.integers(18, 76, size=N_CUSTOMERS)

    income = np.clip(
        rng.normal(
            loc=115_000,
            scale=55_000,
            size=N_CUSTOMERS,
        ),
        30_000,
        350_000,
    ).round(2)

    credit_score = np.clip(
        rng.normal(
            loc=655,
            scale=70,
            size=N_CUSTOMERS,
        ),
        300,
        850,
    ).round().astype(int)

    default_probability = np.where(
        credit_score < 580,
        0.18,
        np.where(
            credit_score < 670,
            0.08,
            0.025,
        ),
    )

    defaulted = (
        rng.random(N_CUSTOMERS) < default_probability
    ).astype(int)

    return pd.DataFrame(
        {
            "customer_id": customer_ids,
            "customer_type": rng.choice(
                CUSTOMER_TYPES,
                N_CUSTOMERS,
                p=[0.45, 0.35, 0.20],
            ),
            "gender": rng.choice(
                ["Female", "Male"],
                N_CUSTOMERS,
            ),
            "age": age,
            "region": rng.choice(
                REGIONS,
                N_CUSTOMERS,
            ),
            "job_type": rng.choice(
                JOB_TYPES,
                N_CUSTOMERS,
            ),
            "annual_income": income,
            "current_credit_score": credit_score,
            "defaulted_flag": defaulted,
            "created_date": random_dates(N_CUSTOMERS),
        }
    )


def generate_applications(
    customers: pd.DataFrame,
    devices: pd.DataFrame,
) -> pd.DataFrame:

    customer_ids = rng.choice(
        customers["customer_id"],
        N_APPLICATIONS,
    )

    customer_lookup = customers.set_index(
        "customer_id"
    )

    credit_scores = (
        customer_lookup
        .loc[customer_ids, "current_credit_score"]
        .to_numpy()
    )

    incomes = (
        customer_lookup
        .loc[customer_ids, "annual_income"]
        .to_numpy()
    )

    requested_amount = np.clip(
        rng.lognormal(
            mean=np.log(45_000),
            sigma=0.75,
            size=N_APPLICATIONS,
        ),
        2_000,
        500_000,
    ).round(2)

    risk_probability = (
        0.24
        - ((credit_scores - 300) / 550) * 0.18
        + rng.normal(0, 0.025, N_APPLICATIONS)
    )

    risk_probability = np.clip(
        risk_probability,
        0.01,
        0.40,
    )

    approval_probability = np.clip(
        0.85
        - risk_probability * 2
        + np.minimum(incomes / 500_000, 0.15),
        0.15,
        0.90,
    )

    approved = (
        rng.random(N_APPLICATIONS)
        < approval_probability
    )

    statuses = np.where(
        approved,
        rng.choice(
            ["Active", "Closed", "Default"],
            N_APPLICATIONS,
            p=[0.72, 0.21, 0.07],
        ),
        "Not Approved",
    )

    fraud_probability = np.clip(
        0.035
        + risk_probability * 0.30,
        0.02,
        0.16,
    )

    fraud_flag = (
        rng.random(N_APPLICATIONS)
        < fraud_probability
    ).astype(int)

    fraud_reason = np.where(
        fraud_flag == 1,
        rng.choice(
            APPLICATION_FRAUD_REASONS,
            N_APPLICATIONS,
        ),
        None,
    )

    return pd.DataFrame(
        {
            "application_id": np.arange(
                1,
                N_APPLICATIONS + 1,
            ),
            "customer_id": customer_ids,
            "device_id": rng.choice(
                devices["device_id"],
                N_APPLICATIONS,
            ),
            "application_date": random_dates(
                N_APPLICATIONS
            ),
            "requested_loan_amount": requested_amount,
            "offered_interest_rate": np.clip(
                5
                + risk_probability * 70
                + rng.normal(
                    0,
                    1.5,
                    N_APPLICATIONS,
                ),
                4,
                30,
            ).round(2),
            "risk_probability": risk_probability.round(4),
            "loan_status": statuses,
            "loan_purpose": rng.choice(
                LOAN_PURPOSES,
                N_APPLICATIONS,
            ),
            "suspected_fraud_flag": fraud_flag,
            "fraud_reason": fraud_reason,
        }
    )


def generate_transactions(
    customers: pd.DataFrame,
    devices: pd.DataFrame,
) -> pd.DataFrame:

    customer_ids = rng.choice(
        customers["customer_id"],
        N_TRANSACTIONS,
    )

    device_ids = rng.choice(
        devices["device_id"],
        N_TRANSACTIONS,
    )

    device_lookup = devices.set_index(
        "device_id"
    )

    prior_device_fraud = (
        device_lookup
        .loc[device_ids, "has_prior_fraud_flag"]
        .to_numpy()
    )

    amount = np.clip(
        rng.lognormal(
            mean=np.log(250),
            sigma=1.15,
            size=N_TRANSACTIONS,
        ),
        2,
        25_000,
    ).round(2)

    fraud_probability = (
        0.0035
        + prior_device_fraud * 0.005
        + np.where(
            amount > 5_000,
            0.004,
            0,
        )
    )

    fraud_flag = (
        rng.random(N_TRANSACTIONS)
        < fraud_probability
    ).astype(int)

    fraud_reason = np.where(
        fraud_flag == 1,
        rng.choice(
            TRANSACTION_FRAUD_REASONS,
            N_TRANSACTIONS,
        ),
        None,
    )

    transaction_type = rng.choice(
        TRANSACTION_TYPES,
        N_TRANSACTIONS,
        p=[0.48, 0.20, 0.12, 0.15, 0.05],
    )

    return_flag = (
        transaction_type == "Return"
    ).astype(int)

    return pd.DataFrame(
        {
            "transaction_id": np.arange(
                1,
                N_TRANSACTIONS + 1,
            ),
            "customer_id": customer_ids,
            "device_id": device_ids,
            "transaction_date": random_dates(
                N_TRANSACTIONS
            ),
            "transaction_type": transaction_type,
            "merchant_category": rng.choice(
                MERCHANT_CATEGORIES,
                N_TRANSACTIONS,
            ),
            "amount": amount,
            "fraudulent_flag": fraud_flag,
            "fraud_reason": fraud_reason,
            "return_flag": return_flag,
        }
    )


def main():
    OUTPUT_DIR.mkdir(
        parents=True,
        exist_ok=True,
    )

    print("Generating synthetic devices...")
    devices = generate_devices()

    print("Generating synthetic customers...")
    customers = generate_customers()

    print("Generating synthetic applications...")
    applications = generate_applications(
        customers,
        devices,
    )

    print("Generating synthetic transactions...")
    transactions = generate_transactions(
        customers,
        devices,
    )

    datasets = {
        "devices.csv": devices,
        "customers.csv": customers,
        "applications.csv": applications,
        "transactions.csv": transactions,
    }

    for filename, dataframe in datasets.items():
        output_path = OUTPUT_DIR / filename

        dataframe.to_csv(
            output_path,
            index=False,
        )

        print(
            f"{filename}: "
            f"{len(dataframe):,} rows"
        )

    print("\nSynthetic data generation completed.")


if __name__ == "__main__":
    main()
